// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"refernet/internal/ent/company"
	"refernet/internal/ent/predicate"
	"refernet/internal/ent/workexperience"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CompanyUpdate is the builder for updating Company entities.
type CompanyUpdate struct {
	config
	hooks    []Hook
	mutation *CompanyMutation
}

// Where appends a list predicates to the CompanyUpdate builder.
func (cu *CompanyUpdate) Where(ps ...predicate.Company) *CompanyUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CompanyUpdate) SetUpdatedAt(t time.Time) *CompanyUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableUpdatedAt(t *time.Time) *CompanyUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// SetName sets the "name" field.
func (cu *CompanyUpdate) SetName(s string) *CompanyUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetOverview sets the "overview" field.
func (cu *CompanyUpdate) SetOverview(s string) *CompanyUpdate {
	cu.mutation.SetOverview(s)
	return cu
}

// SetWebsite sets the "website" field.
func (cu *CompanyUpdate) SetWebsite(s string) *CompanyUpdate {
	cu.mutation.SetWebsite(s)
	return cu
}

// SetLogoURL sets the "logo_url" field.
func (cu *CompanyUpdate) SetLogoURL(s string) *CompanyUpdate {
	cu.mutation.SetLogoURL(s)
	return cu
}

// SetSize sets the "size" field.
func (cu *CompanyUpdate) SetSize(c company.Size) *CompanyUpdate {
	cu.mutation.SetSize(c)
	return cu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (cu *CompanyUpdate) SetNillableSize(c *company.Size) *CompanyUpdate {
	if c != nil {
		cu.SetSize(*c)
	}
	return cu
}

// SetFoundedAt sets the "founded_at" field.
func (cu *CompanyUpdate) SetFoundedAt(i int) *CompanyUpdate {
	cu.mutation.ResetFoundedAt()
	cu.mutation.SetFoundedAt(i)
	return cu
}

// AddFoundedAt adds i to the "founded_at" field.
func (cu *CompanyUpdate) AddFoundedAt(i int) *CompanyUpdate {
	cu.mutation.AddFoundedAt(i)
	return cu
}

// AddStaffIDs adds the "staffs" edge to the WorkExperience entity by IDs.
func (cu *CompanyUpdate) AddStaffIDs(ids ...int) *CompanyUpdate {
	cu.mutation.AddStaffIDs(ids...)
	return cu
}

// AddStaffs adds the "staffs" edges to the WorkExperience entity.
func (cu *CompanyUpdate) AddStaffs(w ...*WorkExperience) *CompanyUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return cu.AddStaffIDs(ids...)
}

// Mutation returns the CompanyMutation object of the builder.
func (cu *CompanyUpdate) Mutation() *CompanyMutation {
	return cu.mutation
}

// ClearStaffs clears all "staffs" edges to the WorkExperience entity.
func (cu *CompanyUpdate) ClearStaffs() *CompanyUpdate {
	cu.mutation.ClearStaffs()
	return cu
}

// RemoveStaffIDs removes the "staffs" edge to WorkExperience entities by IDs.
func (cu *CompanyUpdate) RemoveStaffIDs(ids ...int) *CompanyUpdate {
	cu.mutation.RemoveStaffIDs(ids...)
	return cu
}

// RemoveStaffs removes "staffs" edges to WorkExperience entities.
func (cu *CompanyUpdate) RemoveStaffs(w ...*WorkExperience) *CompanyUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return cu.RemoveStaffIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CompanyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CompanyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CompanyUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CompanyUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CompanyUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CompanyUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := company.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Overview(); ok {
		if err := company.OverviewValidator(v); err != nil {
			return &ValidationError{Name: "overview", err: fmt.Errorf("ent: validator failed for field \"overview\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Website(); ok {
		if err := company.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf("ent: validator failed for field \"website\": %w", err)}
		}
	}
	if v, ok := cu.mutation.LogoURL(); ok {
		if err := company.LogoURLValidator(v); err != nil {
			return &ValidationError{Name: "logo_url", err: fmt.Errorf("ent: validator failed for field \"logo_url\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Size(); ok {
		if err := company.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf("ent: validator failed for field \"size\": %w", err)}
		}
	}
	if v, ok := cu.mutation.FoundedAt(); ok {
		if err := company.FoundedAtValidator(v); err != nil {
			return &ValidationError{Name: "founded_at", err: fmt.Errorf("ent: validator failed for field \"founded_at\": %w", err)}
		}
	}
	return nil
}

func (cu *CompanyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   company.Table,
			Columns: company.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: company.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: company.FieldUpdatedAt,
		})
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldName,
		})
	}
	if value, ok := cu.mutation.Overview(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldOverview,
		})
	}
	if value, ok := cu.mutation.Website(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldWebsite,
		})
	}
	if value, ok := cu.mutation.LogoURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldLogoURL,
		})
	}
	if value, ok := cu.mutation.Size(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: company.FieldSize,
		})
	}
	if value, ok := cu.mutation.FoundedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: company.FieldFoundedAt,
		})
	}
	if value, ok := cu.mutation.AddedFoundedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: company.FieldFoundedAt,
		})
	}
	if cu.mutation.StaffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedStaffsIDs(); len(nodes) > 0 && !cu.mutation.StaffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.StaffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CompanyUpdateOne is the builder for updating a single Company entity.
type CompanyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompanyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CompanyUpdateOne) SetUpdatedAt(t time.Time) *CompanyUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableUpdatedAt(t *time.Time) *CompanyUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// SetName sets the "name" field.
func (cuo *CompanyUpdateOne) SetName(s string) *CompanyUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetOverview sets the "overview" field.
func (cuo *CompanyUpdateOne) SetOverview(s string) *CompanyUpdateOne {
	cuo.mutation.SetOverview(s)
	return cuo
}

// SetWebsite sets the "website" field.
func (cuo *CompanyUpdateOne) SetWebsite(s string) *CompanyUpdateOne {
	cuo.mutation.SetWebsite(s)
	return cuo
}

// SetLogoURL sets the "logo_url" field.
func (cuo *CompanyUpdateOne) SetLogoURL(s string) *CompanyUpdateOne {
	cuo.mutation.SetLogoURL(s)
	return cuo
}

// SetSize sets the "size" field.
func (cuo *CompanyUpdateOne) SetSize(c company.Size) *CompanyUpdateOne {
	cuo.mutation.SetSize(c)
	return cuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (cuo *CompanyUpdateOne) SetNillableSize(c *company.Size) *CompanyUpdateOne {
	if c != nil {
		cuo.SetSize(*c)
	}
	return cuo
}

// SetFoundedAt sets the "founded_at" field.
func (cuo *CompanyUpdateOne) SetFoundedAt(i int) *CompanyUpdateOne {
	cuo.mutation.ResetFoundedAt()
	cuo.mutation.SetFoundedAt(i)
	return cuo
}

// AddFoundedAt adds i to the "founded_at" field.
func (cuo *CompanyUpdateOne) AddFoundedAt(i int) *CompanyUpdateOne {
	cuo.mutation.AddFoundedAt(i)
	return cuo
}

// AddStaffIDs adds the "staffs" edge to the WorkExperience entity by IDs.
func (cuo *CompanyUpdateOne) AddStaffIDs(ids ...int) *CompanyUpdateOne {
	cuo.mutation.AddStaffIDs(ids...)
	return cuo
}

// AddStaffs adds the "staffs" edges to the WorkExperience entity.
func (cuo *CompanyUpdateOne) AddStaffs(w ...*WorkExperience) *CompanyUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return cuo.AddStaffIDs(ids...)
}

// Mutation returns the CompanyMutation object of the builder.
func (cuo *CompanyUpdateOne) Mutation() *CompanyMutation {
	return cuo.mutation
}

// ClearStaffs clears all "staffs" edges to the WorkExperience entity.
func (cuo *CompanyUpdateOne) ClearStaffs() *CompanyUpdateOne {
	cuo.mutation.ClearStaffs()
	return cuo
}

// RemoveStaffIDs removes the "staffs" edge to WorkExperience entities by IDs.
func (cuo *CompanyUpdateOne) RemoveStaffIDs(ids ...int) *CompanyUpdateOne {
	cuo.mutation.RemoveStaffIDs(ids...)
	return cuo
}

// RemoveStaffs removes "staffs" edges to WorkExperience entities.
func (cuo *CompanyUpdateOne) RemoveStaffs(w ...*WorkExperience) *CompanyUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return cuo.RemoveStaffIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CompanyUpdateOne) Select(field string, fields ...string) *CompanyUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Company entity.
func (cuo *CompanyUpdateOne) Save(ctx context.Context) (*Company, error) {
	var (
		err  error
		node *Company
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CompanyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CompanyUpdateOne) SaveX(ctx context.Context) *Company {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CompanyUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CompanyUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CompanyUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := company.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Overview(); ok {
		if err := company.OverviewValidator(v); err != nil {
			return &ValidationError{Name: "overview", err: fmt.Errorf("ent: validator failed for field \"overview\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Website(); ok {
		if err := company.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf("ent: validator failed for field \"website\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.LogoURL(); ok {
		if err := company.LogoURLValidator(v); err != nil {
			return &ValidationError{Name: "logo_url", err: fmt.Errorf("ent: validator failed for field \"logo_url\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Size(); ok {
		if err := company.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf("ent: validator failed for field \"size\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.FoundedAt(); ok {
		if err := company.FoundedAtValidator(v); err != nil {
			return &ValidationError{Name: "founded_at", err: fmt.Errorf("ent: validator failed for field \"founded_at\": %w", err)}
		}
	}
	return nil
}

func (cuo *CompanyUpdateOne) sqlSave(ctx context.Context) (_node *Company, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   company.Table,
			Columns: company.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: company.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Company.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, company.FieldID)
		for _, f := range fields {
			if !company.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != company.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: company.FieldUpdatedAt,
		})
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldName,
		})
	}
	if value, ok := cuo.mutation.Overview(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldOverview,
		})
	}
	if value, ok := cuo.mutation.Website(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldWebsite,
		})
	}
	if value, ok := cuo.mutation.LogoURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: company.FieldLogoURL,
		})
	}
	if value, ok := cuo.mutation.Size(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: company.FieldSize,
		})
	}
	if value, ok := cuo.mutation.FoundedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: company.FieldFoundedAt,
		})
	}
	if value, ok := cuo.mutation.AddedFoundedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: company.FieldFoundedAt,
		})
	}
	if cuo.mutation.StaffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedStaffsIDs(); len(nodes) > 0 && !cuo.mutation.StaffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.StaffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   company.StaffsTable,
			Columns: []string{company.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: workexperience.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Company{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{company.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
