// Code generated by entc, DO NOT EDIT.

package skill

import (
	"refernet/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// DarkLogoURL applies equality check predicate on the "dark_logo_url" field. It's identical to DarkLogoURLEQ.
func DarkLogoURL(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDarkLogoURL), v))
	})
}

// LightLogoURL applies equality check predicate on the "light_logo_url" field. It's identical to LightLogoURLEQ.
func LightLogoURL(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLightLogoURL), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// DarkLogoURLEQ applies the EQ predicate on the "dark_logo_url" field.
func DarkLogoURLEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLNEQ applies the NEQ predicate on the "dark_logo_url" field.
func DarkLogoURLNEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLIn applies the In predicate on the "dark_logo_url" field.
func DarkLogoURLIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDarkLogoURL), v...))
	})
}

// DarkLogoURLNotIn applies the NotIn predicate on the "dark_logo_url" field.
func DarkLogoURLNotIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDarkLogoURL), v...))
	})
}

// DarkLogoURLGT applies the GT predicate on the "dark_logo_url" field.
func DarkLogoURLGT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLGTE applies the GTE predicate on the "dark_logo_url" field.
func DarkLogoURLGTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLLT applies the LT predicate on the "dark_logo_url" field.
func DarkLogoURLLT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLLTE applies the LTE predicate on the "dark_logo_url" field.
func DarkLogoURLLTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLContains applies the Contains predicate on the "dark_logo_url" field.
func DarkLogoURLContains(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLHasPrefix applies the HasPrefix predicate on the "dark_logo_url" field.
func DarkLogoURLHasPrefix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLHasSuffix applies the HasSuffix predicate on the "dark_logo_url" field.
func DarkLogoURLHasSuffix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLEqualFold applies the EqualFold predicate on the "dark_logo_url" field.
func DarkLogoURLEqualFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDarkLogoURL), v))
	})
}

// DarkLogoURLContainsFold applies the ContainsFold predicate on the "dark_logo_url" field.
func DarkLogoURLContainsFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDarkLogoURL), v))
	})
}

// LightLogoURLEQ applies the EQ predicate on the "light_logo_url" field.
func LightLogoURLEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLNEQ applies the NEQ predicate on the "light_logo_url" field.
func LightLogoURLNEQ(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLIn applies the In predicate on the "light_logo_url" field.
func LightLogoURLIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLightLogoURL), v...))
	})
}

// LightLogoURLNotIn applies the NotIn predicate on the "light_logo_url" field.
func LightLogoURLNotIn(vs ...string) predicate.Skill {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Skill(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLightLogoURL), v...))
	})
}

// LightLogoURLGT applies the GT predicate on the "light_logo_url" field.
func LightLogoURLGT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLGTE applies the GTE predicate on the "light_logo_url" field.
func LightLogoURLGTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLLT applies the LT predicate on the "light_logo_url" field.
func LightLogoURLLT(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLLTE applies the LTE predicate on the "light_logo_url" field.
func LightLogoURLLTE(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLContains applies the Contains predicate on the "light_logo_url" field.
func LightLogoURLContains(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLHasPrefix applies the HasPrefix predicate on the "light_logo_url" field.
func LightLogoURLHasPrefix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLHasSuffix applies the HasSuffix predicate on the "light_logo_url" field.
func LightLogoURLHasSuffix(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLEqualFold applies the EqualFold predicate on the "light_logo_url" field.
func LightLogoURLEqualFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLightLogoURL), v))
	})
}

// LightLogoURLContainsFold applies the ContainsFold predicate on the "light_logo_url" field.
func LightLogoURLContainsFold(v string) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLightLogoURL), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Skill) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		p(s.Not())
	})
}
